In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [4]:
df=pd.read_csv('stud.csv')
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [4]:
df.shape

(30, 8)

In [5]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       30 non-null     object
 1   race_ethnicity               30 non-null     object
 2   parental_level_of_education  30 non-null     object
 3   lunch                        30 non-null     object
 4   test_preparation_course      30 non-null     object
 5   math_score                   30 non-null     int64
 6   reading_score                30 non-null     int64
 7   writing_score                30 non-null     int64
dtypes: int64(3), object(5)
memory usage: 2.0+ KB

In [8]:
df.describe()

       math_score  reading_score  writing_score
count   30.000000      30.000000      30.000000
mean    68.366667      73.733333      71.266667
std     16.116993      15.558418      17.304441
min     38.000000      43.000000      39.000000
25%     55.750000      60.000000      55.500000
50%     70.000000      75.500000      74.500000
75%     80.500000      87.250000      87.000000
max     92.000000      96.000000      96.000000

In [10]:
df['gender'].unique()

array(['female', 'male'], dtype=object)

In [4]:
numeric_feature=[feature for feature in df.columns if df[feature].dtype!='O']
categorical_feature=[feature for feature in df.columns if df[feature].dtype=='O']
print('Numeric feature:',numeric_feature)
print('\nCategorical feature:',categorical_feature)

Numeric feature: ['math_score', 'reading_score', 'writing_score']

Categorical feature: ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

In [6]:
df['total_score']=df['math_score']+df['reading_score']+df['writing_score']
df['average_score']=df['total_score']/3
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,total_score,average_score
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333